React sample: For review
DevExpress-Examples/devextreme-datagrid-customize-edit-form-buttons pull request #3
Opened 2023-05-17 12:00 UTC by DuckTieCorpMember

2023-05-18 13:48 UTC, artem-kurchenko commented on React/src/components/EditingPopup.tsx
> +        (grid.current as any).instance.cancelEditData();
Any looks strange here

try defining ref as follows:
const grid = useRef<DataGrid>(null);

See https://github.com/DevExpress-Examples/devextreme-datagrid-hide-show-edit-form-items-dynamically/blob/22.2.3%2B/React/src/App.tsx#L57

2023-05-18 13:50 UTC, artem-kurchenko commented on React/src/components/EditingPopup.tsx
> +        const gridInstance = (grid.current as any).instance;
same for `any` here

2023-05-18 13:50 UTC, artem-kurchenko commented on React/src/components/EditingPopup.tsx
> +    const saveOptions = {
You need either to memorize consts or move them outside the component where it's possible

2023-05-19 11:32 UTC, DuckTieCorpMember commented
Added new commit with required changes.

2023-05-22 04:58 UTC, artem-kurchenko approved these changes

2023-05-22 08:24 UTC, flagmanAndrew requested changes

2023-05-22 08:24 UTC, flagmanAndrew commented on React/src/components/EditingForm.tsx
> +    const saveButtonClick = useCallback((e:ClickEvent) => {
You can simplify this part. Remove useCallback and put this function directly in saveOptions.onClick. The same for other buttons.

2023-05-22 08:24 UTC, flagmanAndrew commented on React/src/components/EditingForm.tsx
> +    const formToolbar = () => {
since formToolbar is a function declared inside a function component, it is better to use useCallback to declare it

2023-05-22 08:24 UTC, flagmanAndrew commented on React/src/components/EditingPopup.tsx
> +    const saveButtonClick = useCallback((e:ClickEvent) => {
Simplify this part following my comment in EditingForm.

2023-05-22 12:40 UTC, DuckTieCorpMember commented
Applied requested changes

2023-05-30 16:13 UTC, merged